# docker-compose for local testing
# containers are prod-ready and can communicate with each other
# same images will be pushed to ecr


services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: users-backend
    restart: unless-stopped
    ports:
      - "8000:8000"  # expose for local testing
    environment:
      - PORT=8000
      - SECRET_KEY=$${#####REMEMBER TO CHANGE WHEN APPLYING TO KUBERNETES!!!!#####}      #flask REQUIRES! it for cookies and stuff
      - CORS_ORIGINS=http://localhost:8080,http://frontend:8080
      - FLASK_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: users-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"  # expose for local testing
    environment:
      # tell frontend where backend is (for local testing)
      - VITE_API_BASE=http://backend:8000/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge